draw_config:
  key_w: 60
  key_h: 56
  combo_w: 28
  combo_h: 26
  dark_mode: true
  append_colon_to_layer_header: false
  draw_key_sides: true
  footer_text: ''

parse_config:
  trans_legend:
    t: ''
    type: trans
  zmk_keycode_map:
    C_PP: 'PLAY PAUSE'
